# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # TwoStepVerificationController
  class TwoStepVerificationController < BaseController
    # You are required to set up two-step verification for your phone number, as
    # this provides an extra layer of security to the business accounts. You can
    # use this endpoint to change two-step verification code associated with
    # your account.
    # After you change the verification code, future requests like changing the
    # name, must use the new code.
    # You set up two-factor verification and register a phone number in the same
    # API call.
    # @param [String] phone_number_id Required parameter: Example:
    # @param [SetTwoStepVerificationCodeRequest] body Required parameter:
    # Example:
    # @return [SuccessResponse] response from the API call
    def set_two_step_verification_code(phone_number_id,
                                       body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/{Phone-Number-ID}',
                                     Server::DEFAULT)
                   .template_param(new_parameter(phone_number_id, key: 'Phone-Number-ID')
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(Single.new('global')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(SuccessResponse.method(:from_hash)))
        .execute
    end
  end
end
