# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Represents a single Http Request.
  class HttpRequest < CoreLibrary::HttpRequest
  end
end
